POST https://api-sd-oqhn.onrender.com/usuarios
Content-Type: application/json

{
    "nome": "joao",
    "email": "test@test.com.br",
    "senha": "teste"
}

###

GET https://api-sd-oqhn.onrender.com/usuarios?search=
###

PUT https://api-sd-oqhn.onrender.com/usuarios/5ea778b4-c839-4fe0-aa5f-40c34c1da001
Content-Type: application/json

{
    "nome": "caio",
    "email": "caioba@gmail.com",
    "senha": "123"
}


###

DELETE https://api-sd-oqhn.onrender.com/usuarios/597f08dc-4048-4e9e-9e34-6b701a018a8c

###

POST https://api-sd-oqhn.onrender.com/categoria
Content-Type: application/json

{
    "nome": "Café em grãos"
}

###

GET https://api-sd-oqhn.onrender.com/categoria?search=

###

DELETE https://api-sd-oqhn.onrender.com/categoria/1

###

POST https://api-sd-oqhn.onrender.com/produtos
Content-Type: application/json

{
    "nome": "Café 100% Arábica 1Kg",
    "description": "Grãos de café 100 Arábica",
    "preco": 50.00,
    "categoriaId": 1
}

###

GET https://api-sd-oqhn.onrender.com/produtos?search=

###

PUT https://api-sd-oqhn.onrender.com/produtos/1
Content-Type: application/json

{
    "nome": "Café com leite",
    "description": "Café coado acrescido com leite morno",
    "preco": 4.00,
    "categoriaId": 1
}


###

DELETE https://api-sd-oqhn.onrender.com/produtos/1
