POST http://localhost:3333/usuarios
Content-Type: application/json

{
    "nome": "joao",
    "email": "test@test.com.br",
    "senha": "teste"
}

###

GET http://localhost:3333/usuarios?search=
###

PUT http://localhost:3333/usuarios/5ea778b4-c839-4fe0-aa5f-40c34c1da001
Content-Type: application/json

{
    "nome": "caio",
    "email": "mamuteesbelto@gamail.com",
    "senha": "71623871263782163781ahnsujd"
}


###

DELETE http://localhost:3333/usuarios/6f879155-5925-4771-a47e-ccdb1b5bb243

###

POST http://localhost:3333/categoria
Content-Type: application/json

{
    "nome": "Café em grãos"
}

###

GET http://localhost:3333/categoria?search=

###

DELETE http://localhost:3333/categoria/1

###

POST http://localhost:3333/produtos
Content-Type: application/json

{
    "nome": "Café 100% Arábica 1Kg",
    "description": "Grãos de café 100 Arábica",
    "preco": 50.00,
    "categoriaId": 1
}

###

GET http://localhost:3333/produtos?search=

###

PUT http://localhost:3333/produtos/1
Content-Type: application/json

{
    "nome": "Café com leite",
    "description": "Café coado acrescido com leite morno",
    "preco": 4.00,
    "categoriaId": 1
}


###

DELETE http://localhost:3333/produtos/1
